### ISSUE TITLE
No longer working with modern versions of ARMIPS, blz and ndstools

### ISSUE THREAD

**Issue by extherian** [StraDaMa/Legend-of-Zelda-Spirit-Tracks-D-Pad-Patch#3]
I obtained these dependencies from [here](https://github.com/Kingcom/armips), [here ](https://github.com/PeterLemon/Nintendo_DS_Compressors)and [here](https://wii.leseratte10.de/devkitPro/other-stuff/ndstool/). However, putting an EU copy of Spirit Tracks as "input.nds" in the input folder and running compile.bat produces a ROM that is unusable, as it hangs at a white screen when loaded in melonDS. Input.nds is my own legally dumped copy of the game, so it's not that I am using a bad dump. I have uploaded a zip file with the dependencies I am using. 

[dependencies.zip](https://github.com/user-attachments/files/16644605/dependencies.zip)

I admit that I do not know for sure if it's the dependencies that are at fault, but compile.bat gives me no useful error messages to troubleshoot and appears to run successfully, so I am at a loss as to what to do.

**Comment by StraDaMa** [comment]
If you read the output of `compile.bat` it gives plenty of error messages
```
BLZ - (c) CUE 2011
Bottom LZ coding for Nintendo GBA/DS

Filenames not specified
```
It seems at some point blz updated to require specifying both an input and output file instead of just compressing/decompressing the input file. A quick fix to just get this working would be to modify every time the scripts run blz and add the same file as the input and output.
For example
```
blz -eo arm9_compressed.bin
```
would be modified to
```
blz -eo arm9_compressed.bin arm9_compressed.bin
```
blz is used in both `prepare.bat` and `compile.bat`

**Comment by extherian** [comment]
Thanks, this worked. I have uploaded a copy of the patch files with corrected versions of prepare.bat and compile.bat, please replace the existing code on your Github with this zip file for anyone else who wants to use it. There is an existing version of this script out there but it was made to work with a known bad dump of Spirit Tracks, so this is the only way to get it working with a good dump. 
[Legend-of-Zelda-Spirit-Tracks-D-Pad-Patch-master.zip](https://github.com/user-attachments/files/16994782/Legend-of-Zelda-Spirit-Tracks-D-Pad-Patch-master.zip)
